"""init

Revision ID: 460d43b5f973
Revises:
Create Date: 2025-04-21 04:29:45.469206

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "460d43b5f973"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_address", sa.String(), nullable=False),
        sa.Column("balance", sa.BigInteger(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("bandwidth", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_request_wallet_id"), "request_wallet", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_request_wallet_wallet_address"),
        "request_wallet",
        ["wallet_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_wallet_wallet_address"), table_name="request_wallet")
    op.drop_index(op.f("ix_request_wallet_id"), table_name="request_wallet")
    op.drop_table("request_wallet")
    # ### end Alembic commands ###
